"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { StockLogo } from "@/components/stock-logo";
import styles from "@/app/app/automation/automation.module.css";

type Kind = "limit" | "stop" | "oco" | "dca";
type Asset = { symbol: string; name: string };
type Draft = { id: string; kind: Kind; symbol: string; side: "buy" | "sell"; shares: number; trigger?: number; takeProfit?: number; stopLoss?: number; cadence?: string; rounds?: number; createdAt: string };
type Wallet = { publicKey?: { toString: () => string } | null; connect: () => Promise<{ publicKey?: { toString: () => string } | null }> };
type Quote = { referencePrice?: number | null; pool?: { priceUsd?: number | null } };

const rules: Record<Kind, { label: string; title: string; description: string }> = {
  limit: { label: "Limit", title: "Enter at a level.", description: "Wait for a price, then act once." },
  stop: { label: "Stop-loss", title: "Protect a position.", description: "Sell if the market falls through your floor." },
  oco: { label: "OCO", title: "Take profit or cut risk.", description: "The first exit cancels the other." },
  dca: { label: "DCA", title: "Build on a rhythm.", description: "Buy the same amount on a schedule." },
};

function getWallet() { const current = window as Window & { solana?: Wallet; solflare?: Wallet }; return current.solana ?? current.solflare ?? null; }
function usd(value: number | null) { return value === null || !Number.isFinite(value) ? "—" : `$${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export function OrderAutomation({ assets }: { assets: Asset[] }) { const params = useSearchParams(); const requestedAsset = params.get("asset"); const initialSymbol = assets.find((item) => item.symbol === requestedAsset)?.symbol ?? assets[0]?.symbol ?? "AAPLx";
  const [kind, setKind] = useState<Kind>("limit"); const [symbol, setSymbol] = useState(initialSymbol); const [side, setSide] = useState<"buy" | "sell">("buy");
  const [shares, setShares] = useState("1"); const [trigger, setTrigger] = useState(""); const [takeProfit, setTakeProfit] = useState(""); const [stopLoss, setStopLoss] = useState(""); const [cadence, setCadence] = useState("weekly"); const [rounds, setRounds] = useState("4");
  const [price, setPrice] = useState<number | null>(null); const [reference, setReference] = useState<number | null>(null); const [wallet, setWallet] = useState<string | null>(null); const [drafts, setDrafts] = useState<Draft[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const asset = assets.find((item) => item.symbol === symbol) ?? { symbol, name: symbol }; const copy = rules[kind]; const amount = Number(shares); const roundCount = kind === "dca" ? Math.max(2, Number(rounds) || 0) : 1; const selectedSide = kind === "oco" ? "sell" : kind === "dca" ? "buy" : side; const current = price ?? reference; const estimated = current !== null && Number.isFinite(amount) && amount > 0 ? current * amount * roundCount : null;

  useEffect(() => { let cancelled = false; setLoading(true); fetch(`/api/analytics/${encodeURIComponent(symbol)}?timeframe=1h`).then((response) => response.ok ? response.json() as Promise<Quote> : Promise.reject(new Error("quote"))).then((data) => { if (!cancelled) { setPrice(data.pool?.priceUsd ?? null); setReference(data.referencePrice ?? null); } }).catch(() => { if (!cancelled) { setPrice(null); setReference(null); } }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [symbol]);
  useEffect(() => { try { const stored = JSON.parse(localStorage.getItem("openstock:automation-drafts") ?? "[]") as Draft[]; setDrafts(Array.isArray(stored) ? stored : []); setWallet(getWallet()?.publicKey?.toString() ?? null); } catch { setDrafts([]); } }, []);

  const error = useMemo(() => { if (!Number.isFinite(amount) || amount <= 0) return "Add the amount this rule should control."; if (kind === "dca" && (!Number.isFinite(Number(rounds)) || Number(rounds) < 2)) return "Choose at least two DCA rounds."; if ((kind === "limit" || kind === "stop") && (!Number.isFinite(Number(trigger)) || Number(trigger) <= 0)) return "Set the price that should wake this rule."; if (kind === "oco") { const tp = Number(takeProfit); const sl = Number(stopLoss); if (!Number.isFinite(tp) || !Number.isFinite(sl) || tp <= 0 || sl <= 0) return "Set both exit levels."; if (tp <= sl) return "Take-profit must sit above stop-loss."; } return ""; }, [amount, kind, rounds, stopLoss, takeProfit, trigger]);
  async function connectWallet() { const provider = getWallet(); if (!provider) { setMessage("Install Phantom or Solflare to connect."); return; } try { const result = await provider.connect(); const address = result.publicKey?.toString() ?? provider.publicKey?.toString(); if (!address) throw new Error("Choose an account in your wallet and try again."); setWallet(address); setMessage("Wallet connected. Activation still requires a separate review."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Wallet connection was cancelled."); } }
  function reviewRule(event: FormEvent) { event.preventDefault(); if (!wallet) { void connectWallet(); return; } if (error) { setMessage(error); return; } const draft: Draft = { id: crypto.randomUUID(), kind, symbol, side: selectedSide, shares: amount, trigger: Number(trigger) || undefined, takeProfit: Number(takeProfit) || undefined, stopLoss: Number(stopLoss) || undefined, cadence, rounds: kind === "dca" ? roundCount : undefined, createdAt: new Date().toISOString() }; const next = [draft, ...drafts].slice(0, 20); localStorage.setItem("openstock:automation-drafts", JSON.stringify(next)); setDrafts(next); setMessage("Rule staged. No funds moved and no transaction was signed."); }
  const sentence = kind === "oco" ? `Exit ${amount || "—"} ${symbol} at ${takeProfit || "take-profit"} or ${stopLoss || "stop-loss"}.` : kind === "dca" ? `Buy ${amount || "—"} ${symbol} every ${cadence} for ${roundCount || "—"} rounds.` : `${selectedSide === "buy" ? "Buy" : "Sell"} ${amount || "—"} ${symbol} when price is ${kind === "stop" ? "below" : "at or below"} ${trigger || "your level"}.`;

  return <div className={styles.shell}>
    <header className={styles.hero}><Link href="/app" className={styles.back}>← Back to market</Link><div className={styles.heroGrid}><div><div className={styles.eyebrow}>OpenStock · automation desk</div><h1>Rules that keep<br />watching.</h1></div><p>Set a condition once. OpenStock keeps the context around it, watches the market, and waits for your approval before funds move.</p></div></header>
    <section className={styles.stats} aria-label="Automation status"><div><span>Rules watching</span><strong>{drafts.length}</strong><small>Saved on this device</small></div><div><span>Capital reserved</span><strong>$0.00</strong><small>No active funding</small></div><div><span>Next trigger</span><strong>—</strong><small>Nothing activated</small></div><div><span>Wallet</span><strong>{wallet ? "Connected" : "Not connected"}</strong><small>{wallet ? `${wallet.slice(0, 4)}…${wallet.slice(-4)}` : "Connect only when ready"}</small></div></section>
    <div className={styles.ruleTabs} role="tablist" aria-label="Automation rule type">{(Object.keys(rules) as Kind[]).map((item) => <button key={item} type="button" role="tab" aria-selected={kind === item} className={kind === item ? styles.active : ""} onClick={() => { setKind(item); if (item === "oco") setSide("sell"); if (item === "dca") setSide("buy"); setMessage(""); }}>{rules[item].label}</button>)}</div>
    <div className={styles.layout}>
      <form className={styles.builder} onSubmit={reviewRule}><div className={styles.panelTop}><div><div className={styles.eyebrow}>Build a rule</div><h2>{copy.title}</h2><p>{copy.description}</p></div><span className={wallet ? styles.connected : styles.pending}>{wallet ? "Wallet connected" : "Draft mode"}</span></div><div className={styles.fields}><label>Asset<select value={symbol} onChange={(event) => setSymbol(event.target.value)}>{assets.map((item) => <option value={item.symbol} key={item.symbol}>{item.symbol} · {item.name}</option>)}</select></label><label>Action<div className={styles.segmented}><button type="button" className={side === "buy" ? styles.active : ""} onClick={() => setSide("buy")}>Buy</button><button type="button" className={side === "sell" ? styles.active : ""} onClick={() => setSide("sell")}>Sell</button></div></label><label>Amount in shares<input inputMode="decimal" value={shares} onChange={(event) => setShares(event.target.value)} min="0" step="any" /></label>{(kind === "limit" || kind === "stop") && <label>{kind === "stop" ? "Wake below" : "Wake at or below"}<input inputMode="decimal" value={trigger} onChange={(event) => setTrigger(event.target.value)} placeholder={current ? current.toFixed(2) : "Price level"} min="0" step="any" /></label>}{kind === "oco" && <><label>Take-profit at<input inputMode="decimal" value={takeProfit} onChange={(event) => setTakeProfit(event.target.value)} placeholder="Upside level" min="0" step="any" /></label><label>Stop-loss at<input inputMode="decimal" value={stopLoss} onChange={(event) => setStopLoss(event.target.value)} placeholder="Risk level" min="0" step="any" /></label></>}{kind === "dca" && <><label>Repeat<select value={cadence} onChange={(event) => setCadence(event.target.value)}><option value="daily">Every day</option><option value="weekly">Every week</option><option value="monthly">Every month</option></select></label><label>Rounds<input inputMode="numeric" value={rounds} onChange={(event) => setRounds(event.target.value)} min="2" step="1" /></label></>}</div><div className={styles.quote}><div><span>Estimated size</span><strong>{loading ? "Updating…" : usd(estimated)}</strong></div><div><span>Pool context</span><strong>{usd(price)}</strong></div><div><span>Reference</span><strong>{usd(reference)}</strong></div></div><p className={styles.note}>This creates a reviewable rule. It does not reserve funds, sign a transaction, or activate monitoring.</p>{message && <p className={styles.message} role="status">{message}</p>}<button className={styles.primary} type="submit">{wallet ? "Review activation" : "Connect wallet"}</button></form>
      <aside className={styles.monitor}><div className={styles.monitorHead}><div><div className={styles.eyebrow}>Rule preview</div><h2>Watching {symbol}</h2></div><StockLogo symbol={symbol} size={54} /></div><div className={styles.preview}><span>WHEN</span><strong>{sentence}</strong><small>Uses the selected market context</small></div><div className={styles.timeline}><div className={styles.timelineActive}><span>01</span><div><strong>Define the rule</strong><small>Current step</small></div></div><div><span>02</span><div><strong>Fund and approve</strong><small>Only after review</small></div></div><div><span>03</span><div><strong>Monitor the market</strong><small>Context stays visible</small></div></div><div><span>04</span><div><strong>Execute and receipt</strong><small>Recorded when complete</small></div></div></div><div className={styles.monitorFoot}><span>{asset.name}</span><strong>{loading ? "Refreshing quote" : `${usd(current)} context`}</strong></div></aside>
    </div>
    <section className={styles.queue}><div className={styles.queueHead}><div><div className={styles.eyebrow}>Saved rules</div><h2>Your automation queue.</h2></div><span>{drafts.length} staged</span></div>{drafts.length === 0 ? <p>No rules are staged yet. Build one above when you know what you want the market to do.</p> : <div className={styles.queueList}>{drafts.map((draft) => <Link href={`/app/automation/review?id=${encodeURIComponent(draft.id)}`} className={styles.queueRow} key={draft.id}><StockLogo symbol={draft.symbol} size={38} /><div><strong>{rules[draft.kind].label} · {draft.symbol}</strong><span>{draft.side === "buy" ? "Buy" : "Sell"} {draft.shares} shares · Review required</span></div><em>Review →</em></Link>)}</div>}</section>
  </div>;
}
