"use client";

import { useEffect, useState } from "react";
import { formatAmount } from "@/lib/scaled-amounts";

type TradeRecord = { mode: "review" | "live"; status?: string; symbol: string; name: string; side: "buy" | "sell"; uiAmount: number; referencePrice: number; priceSource?: "official" | "onchain_pool"; multiplier: number; createdAt: string; signature: string | null; wallet?: string };

export function PaperReceipt({ id }: { id: string }) {
  const [record, setRecord] = useState<TradeRecord | null>(null);
  useEffect(() => { let active = true; try { const value = localStorage.getItem("openstock:review:" + id); if (value) setRecord(JSON.parse(value) as TradeRecord); } catch { setRecord(null); } fetch("/api/receipts?id=" + encodeURIComponent(id), { cache: "no-store" }).then((response) => response.ok ? response.json() as Promise<{ receipt: { symbol: string; name: string; side: "buy" | "sell"; shares: number; referencePrice: number; multiplier: number; priceSource: "official" | "onchain_pool"; createdAt: string; signature: string; wallet: string } }> : null).then((payload) => { if (active && payload?.receipt) setRecord({ mode: "live", status: "confirmed", symbol: payload.receipt.symbol, name: payload.receipt.name, side: payload.receipt.side, uiAmount: payload.receipt.shares, referencePrice: payload.receipt.referencePrice, multiplier: payload.receipt.multiplier, priceSource: payload.receipt.priceSource, createdAt: payload.receipt.createdAt, signature: payload.receipt.signature, wallet: payload.receipt.wallet }); }).catch(() => undefined); return () => { active = false; }; }, [id]);
  if (!record) return <section className="panel receipt-empty"><div className="eyebrow">Trade receipt</div><h1>This receipt is no longer on this device.</h1><p>Return to the market to create a new order.</p></section>;
  const isLive = record.mode === "live" && Boolean(record.signature);
  const priceLabel = record.priceSource === "onchain_pool" ? "Onchain price used" : "Official reference used";
  return <section className="panel receipt-card"><div className="receipt-card__top"><div><div className="eyebrow">{isLive ? "Live trade · confirmed" : "Order review · saved locally"}</div><h1>{record.side === "buy" ? "Buy" : "Sell"} {record.symbol}</h1><p>{record.name} · {new Date(record.createdAt).toLocaleString()}</p></div><span className="receipt-card__seal">{isLive ? <>CONFIRMED<br />ON SOLANA</> : <>REVIEW<br />ONLY</>}</span></div><div className="receipt-fields"><div><span>Shares</span><strong>{formatAmount(record.uiAmount)}</strong></div><div><span>Estimated total</span><strong>{"$" + (record.uiAmount * record.referencePrice).toFixed(2)}</strong></div><div><span>Share adjustment</span><strong>{record.multiplier.toFixed(4)}×</strong></div><div><span>{priceLabel}</span><strong>{"$" + record.referencePrice.toFixed(2)}</strong></div><div><span>Wallet</span><strong>{record.wallet ? record.wallet.slice(0, 6) + "…" + record.wallet.slice(-4) : "Not connected"}</strong></div><div><span>Status</span><strong>{isLive ? "Confirmed" : "Ready to confirm"}</strong></div></div>{record.priceSource === "onchain_pool" ? <p className="receipt-card__disclaimer">This order used the live Solana quote because the issuer reference was paused. Check the transaction for final settlement details.</p> : null}{isLive && record.signature ? <p className="receipt-card__disclaimer">Confirmed by Jupiter and recorded on Solana. <a href={"https://solscan.io/tx/" + record.signature} target="_blank" rel="noreferrer">View transaction ↗</a></p> : <p className="receipt-card__disclaimer">Review saved. Your wallet has not confirmed an order yet.</p>}</section>;
}
