import curatedSymbols from "@/lib/curated-symbols.json";

export const XSTOCKS_API_BASE = process.env.XSTOCKS_API_BASE ?? "https://api.xstocks.fi/api/v2";
export const CURATED_SYMBOLS: string[] = curatedSymbols;
type Stablecoin = { symbol?: string; currency?: string; address?: string; decimals?: number; solanaTokenProgram?: "TokenProgram" | "Token2022Program" };
export type XStocksAsset = { id: string; name: string; symbol: string; logo?: string; description?: string; isTradingHalted?: boolean; underlying?: { symbol?: string; type?: "Equity" | "ETF" | null; listingCountry?: string | null } | null; trading?: { isTradingHalted?: boolean; currentPeriod?: "market" | "extended" | "overnight" | "closed"; openNow?: boolean; nextChangeAt?: string | null; exchange?: { abbreviation?: string; name?: string; timezone?: string } | null } | null; deployments?: Array<{ network?: string; address?: string; decimals?: number; stablecoins?: Stablecoin[]; solanaTokenProgram?: "TokenProgram" | "Token2022Program" }> };
export type XStocksMultiplier = { currentMultiplier?: number | null; newMultiplier?: number | null; activationDateTime?: number | string | null; reason?: "FeeAccrual" | "Dividend" | "Split" | "ReverseSplit" | "Administrative" | null };
export type OpenStockAsset = XStocksAsset & { price: number | null; multiplier: XStocksMultiplier | null; solanaDeployment: NonNullable<XStocksAsset["deployments"]>[number] | null };
export class XStocksApiError extends Error { status: number; constructor(message: string, status = 0) { super(message); this.name = "XStocksApiError"; this.status = status; } }
async function getJson<T>(path: string, revalidate = 30): Promise<T> { const response = await fetch(`${XSTOCKS_API_BASE}${path}`, { headers: { Accept: "application/json" }, next: { revalidate }, signal: AbortSignal.timeout(8000) }); if (!response.ok) throw new XStocksApiError(`xStocks returned ${response.status} for ${path}`, response.status); return response.json() as Promise<T>; }
function findSolanaDeployment(asset: XStocksAsset) { return asset.deployments?.find((deployment) => deployment.network === "Solana") ?? null; }
export function solanaProgram(asset: OpenStockAsset) { return asset.solanaDeployment ? "Solana" : "Network data loading"; }
export async function listSolanaAssets(): Promise<XStocksAsset[]> { const response = await getJson<{ nodes?: XStocksAsset[] }>("/public/assets?network=Solana&pageSize=100", 45); return (response.nodes ?? []).filter((asset) => Boolean(asset.symbol && findSolanaDeployment(asset))); }
export async function getAsset(symbol: string): Promise<XStocksAsset> { return getJson<XStocksAsset>(`/public/assets/${encodeURIComponent(symbol)}`); }
export async function getPrice(symbol: string): Promise<{ quote?: number | null }> { return getJson<{ quote?: number | null }>(`/public/assets/${encodeURIComponent(symbol)}/price-data`, 15); }
export async function getMultiplier(symbol: string): Promise<XStocksMultiplier> { return getJson<XStocksMultiplier>(`/public/assets/${encodeURIComponent(symbol)}/multiplier?network=Solana`, 30); }
export async function hydrateAsset(asset: XStocksAsset): Promise<OpenStockAsset> { const [priceResult, multiplierResult] = await Promise.allSettled([getPrice(asset.symbol), getMultiplier(asset.symbol)]); return { ...asset, price: priceResult.status === "fulfilled" ? priceResult.value.quote ?? null : null, multiplier: multiplierResult.status === "fulfilled" ? multiplierResult.value : null, solanaDeployment: findSolanaDeployment(asset) }; }
export async function getHydratedAsset(symbol: string): Promise<OpenStockAsset> { return hydrateAsset(await getAsset(symbol)); }
export function displayPrice(price: number | null | undefined, currency = "USD") { if (price === null || price === undefined || !Number.isFinite(price)) return "Refreshing"; return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(price); }
export function displayPeriod(period: "market" | "extended" | "overnight" | "closed" | undefined) { return period ? period.charAt(0).toUpperCase() + period.slice(1) : "Market phase loading"; }
